name: 'my_alarms'
description: 'Mes Alarmes'
publish_to: 'none'
version: 0.4.0+6

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  crypto: ^3.0.3
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_i18n: ^0.36.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.3
  responsive_grid: ^2.4.4
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  geolocator: ^13.0.1
  local_auth: ^2.2.0
  alarm: ^4.1.1
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.2
  audioplayers: ^6.1.0
  volume_controller: ^2.0.8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/musics/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/my_alarm_icon.png'
  min_sdk_android: 24
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/my_alarm_icon.png'
  adaptive_icon_foreground_inset: 16
  adaptive_icon_monochrome: 'assets/images/my_alarm_icon_monochrome.png'
