name: Build

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build libgtk-3-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - run: flutter pub get


      - name: Update version in pubspec.yaml
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}

          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+-][^[:space:]]+)?$ ]]; then
            echo "Version invalide ($VERSION), utilisation de 0.0.0-nightly"
            VERSION="0.0.0-nightly"
          fi

          sed -i "s/^version: .*/version: $VERSION/" pubspec.yaml
          echo "Version set to: $VERSION"
          grep version pubspec.yaml

      - run: flutter build apk --debug --no-pub

  build-ios:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - name: Update version in pubspec.yaml
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}

          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+-][^[:space:]]+)?$ ]]; then
            echo "Version invalide ($VERSION), utilisation de 0.0.0-nightly"
            VERSION="0.0.0-nightly"
          fi

          sed -i "s/^version: .*/version: $VERSION/" pubspec.yaml
          echo "Version set to: $VERSION"
          grep version pubspec.yaml

      - run: flutter build ios --release --no-pub --no-codesign
